version: '3.4'

services:
  acolyte:
    build:
      context: .
    image: acolyte:${COMMIT}
    depends_on:
      - brain
    environment:
      - ACOLYTE_TWITTER_CONSUMER_KEY=${ACOLYTE_TWITTER_CONSUMER_KEY}
      - ACOLYTE_TWITTER_CONSUMER_SECRET=${ACOLYTE_TWITTER_CONSUMER_SECRET}
      - ACOLYTE_TWITTER_ACCESS_TOKEN_KEY=${ACOLYTE_TWITTER_ACCESS_TOKEN_KEY}
      - ACOLYTE_TWITTER_ACCESS_TOKEN_SECRET=${ACOLYTE_TWITTER_ACCESS_TOKEN_SECRET}
      - ACOLYTE_DISCORD_TOKEN=${ACOLYTE_DISCORD_TOKEN}
    networks:
      - bot_network
  brain:
    image: cbsgen:latest
    container_name: brain
    command: python3 /home/service/main.py pretrain
    expose:
      - 8080
    networks:
      - bot_network
    volumes:
      - ${PWD}/data:/home/service/data

networks:
  bot_network:
